import { StyleSheet } from 'react-native';

export const historyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 16,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  headerTitle: {
    fontSize: 34,
    fontWeight: '700',
    color: '#000',
    letterSpacing: -0.5,
  },
  statsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F2F2F7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  settingsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F2F2F7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewToggle: {
    flexDirection: 'row',
    backgroundColor: '#F2F2F7',
    borderRadius: 9,
    padding: 2,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 7,
    alignItems: 'center',
  },
  toggleButtonActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  toggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#8E8E93',
  },
  toggleTextActive: {
    color: '#000',
  },
  contentContainer: {
    flex: 1,
  },
  viewContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 100,
  },
  dummyDataIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginHorizontal: 24,
    marginBottom: 16,
    gap: 8,
  },
  dummyDataText: {
    fontSize: 12,
    color: '#667eea',
    fontWeight: '500',
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  loadingText: {
    fontSize: 16,
    color: '#667eea',
    marginTop: 16,
    fontWeight: '500',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1d1d1f',
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 16,
    color: '#86868b',
    textAlign: 'center',
  },
});

export const dailyStyles = StyleSheet.create({
  streakBar: {
    height: 60,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  streakInfo: {
    flexDirection: 'column',
  },
  streakLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 2,
  },
  streakNumber: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  badges: {
    flexDirection: 'row',
    gap: 8,
  },
  badge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeEmoji: {
    fontSize: 16,
  },
  daySummary: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  dayDate: {
    fontSize: 13,
    color: '#8E8E93',
    fontWeight: '600',
  },
  entryCount: {
    backgroundColor: '#F2F2F7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  entryCountText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#667eea',
  },
  moodBar: {
    flexDirection: 'row',
    height: 4,
    gap: 4,
    marginBottom: 12,
  },
  moodSegment: {
    height: 4,
    borderRadius: 2,
  },
  highlightTitle: {
    fontSize: 19,
    fontWeight: '600',
    color: '#000',
    marginBottom: 6,
  },
  highlightSnippet: {
    fontSize: 15,
    color: '#3C3C43',
    opacity: 0.7,
    lineHeight: 21,
    marginBottom: 12,
  },
  aiInsightsSection: {
    backgroundColor: 'rgba(102, 126, 234, 0.05)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  aiInsightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 6,
  },
  aiInsightLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#667eea',
  },
  aiInsightText: {
    fontSize: 13,
    color: '#667eea',
    lineHeight: 18,
  },
  dayMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  metaStatText: {
    fontSize: 13,
    color: '#8E8E93',
  },
  chevron: {
    marginLeft: 'auto',
  },
});

export const weeklyStyles = StyleSheet.create({
  weekCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  weekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  weekDates: {
    fontSize: 15,
    fontWeight: '600',
    color: '#000',
  },
  entryCountBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  moodChart: {
    height: 60,
    backgroundColor: '#F8F8FA',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 8,
    gap: 4,
    marginBottom: 16,
  },
  moodChartBar: {
    flex: 1,
    borderRadius: 4,
    minHeight: 8,
    opacity: 0.8,
  },
  weekStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    paddingVertical: 12,
    backgroundColor: '#F8F8FA',
    borderRadius: 12,
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: '#8E8E93',
    fontWeight: '500',
  },
  tagsSection: {
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    marginBottom: 8,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tag: {
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  tagText: {
    fontSize: 12,
    color: '#667eea',
    fontWeight: '500',
  },
  highlightsSection: {
    marginBottom: 12,
  },
  lowlightsSection: {
    marginBottom: 16,
  },
  highlightItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  highlightEmoji: {
    fontSize: 16,
  },
  highlightText: {
    fontSize: 14,
    color: '#3C3C43',
    flex: 1,
    lineHeight: 18,
  },
  aiSummarySection: {
    backgroundColor: 'rgba(102, 126, 234, 0.05)',
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#667eea',
  },
  aiSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 6,
  },
  aiSummaryLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#667eea',
  },
  aiSummaryText: {
    fontSize: 14,
    color: '#667eea',
    lineHeight: 20,
    fontStyle: 'italic',
  },
});

export const monthlyStyles = StyleSheet.create({
  monthHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  monthTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#000',
    marginBottom: 4,
  },
  monthSubtitle: {
    fontSize: 16,
    color: '#8E8E93',
  },
  monthOverviewCard: {
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
  },
  monthStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  monthStatItem: {
    width: '50%',
    alignItems: 'center',
    marginBottom: 12,
  },
  monthStatValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  monthStatLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
  },
  moodTrendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  moodTrendText: {
    fontSize: 14,
    color: 'white',
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  monthCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  monthCardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
    marginBottom: 12,
  },
  monthCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  monthTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  monthTag: {
    backgroundColor: 'rgba(102, 126, 234, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  monthTagText: {
    fontSize: 13,
    color: '#667eea',
    fontWeight: '500',
  },
  emotionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  emotionItem: {
    backgroundColor: '#F8F8FA',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  emotionText: {
    fontSize: 13,
    color: '#3C3C43',
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  monthHighlightItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    gap: 12,
  },
  monthHighlightDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4CAF50',
    marginTop: 6,
  },
  monthHighlightText: {
    fontSize: 14,
    color: '#3C3C43',
    lineHeight: 20,
    flex: 1,
  },
  aiMonthSummaryCard: {
    backgroundColor: 'rgba(102, 126, 234, 0.05)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(102, 126, 234, 0.1)',
  },
  aiMonthSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  aiMonthSummaryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#667eea',
  },
  aiMonthSummaryText: {
    fontSize: 15,
    color: '#667eea',
    lineHeight: 22,
    fontStyle: 'italic',
  },
  insightItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    gap: 8,
  },
  insightText: {
    fontSize: 14,
    color: '#3C3C43',
    lineHeight: 20,
    flex: 1,
  },
});